provide Mattermost settings & less events
BoYanZh/Joint-Teapot pull request #27
Opened 2023-09-26 01:05 UTC by CHHC-L

- In `.env.example`, added Mattermost team and token setting to run `create-channels-on-mm` more easily.
- In `./joint_teapot/workers/mattermost.py`, trigger messages on less events.
- Updated related part of README.

2023-09-26 03:30 UTC, BoYanZh requested changes

2023-09-26 03:30 UTC, BoYanZh commented on README.md
> +Example: `python3 -m joint_teapot create-channels-on-mm --prefix p1 --suffix -private --invite-teaching-team` will fetch all repos whose names start with `"p1"` and create channels on mm for these re
The value in the list can be set with `.env` file.

```
MATTERMOST_TEACHING_TEAM=["A", "B", "C"]
```

2023-09-26 08:50 UTC, wznmickey commented
Where can we get the mattermost token?

2023-09-27 03:32 UTC, CHHC-L commented
Changed `.env.example`.

2023-09-27 03:44 UTC, CHHC-L commented
> Where can we get the mattermost token?

Channel admin should allows a user generate token in `System Console -> User Management,` then the user can get token from his `Profire -> Security -> Personal Access Tokens`. Refer to [this page](https://docs.mattermost.com/developer/personal-access-tokens.html) .

2023-09-28 01:45 UTC, BoYanZh approved these changes

2023-09-28 01:51 UTC, merged