hide healthcheck section if passed
BoYanZh/Joint-Teapot pull request #44
Opened 2024-10-09 13:27 UTC by mQzLjP

> only display health check section if it fails (list all issues as bullet points). if it passes, then don't show anything

This pull request is for this task, but for "list all issue as bullet points", I don't quite know if I need to do anything on my side.

2024-10-09 20:57 UTC, BoYanZh commented
Can we just hide all results with 0 scores and empty comments? The stage with the healthcheck parser can have an arbitrary name.

2024-10-10 01:30 UTC, mQzLjP commented
Done @BoYanZh

2024-10-10 01:30 UTC, BoYanZh requested changes

2024-10-10 01:30 UTC, BoYanZh commented on joint_teapot/utils/joj3.py
> +        for i, result in enumerate(stage["results"]):
`enumerate` is not necessary here

also, consider `stage_score = sum(result["score"] for result in stage["results"])`

2024-10-10 01:30 UTC, BoYanZh commented on joint_teapot/utils/joj3.py
> +        if stage_score == 0 and stage["results"][0]["comment"].strip() == "":
We need to make sure every comment in this stage is empty.

`all(result["comment"].strip() == "" for result in stage["results"])`

2024-10-10 01:42 UTC, BoYanZh commented on joint_teapot/utils/joj3.py
> +        for i, result in enumerate(stage["results"]):
better to check all scores are 0 to avoid a coincidence sum of 0.

2024-10-10 07:24 UTC, merged